image: registry.gitlab.com/olimpiadi-informatica/task-maker/runner:v2

stages:
  - build
  - pack

build_and_test:
  stage: build
  before_script:
    - apt-get update -yy && apt-get upgrade -yy python3-wheel python3-virtualenv virtualenv
    - |
      cat > $CI_PROJECT_DIR/.bazelrc <<EOF
      # This is from Bazel's former travis setup, to avoid blowing up the RAM usage.
      startup --host_jvm_args=-Xmx2500m
      startup --host_jvm_args=-Xms2500m
      startup --batch
      test --ram_utilization_factor=10
      # This is so we understand failures better
      build --verbose_failures
      # This is so we don't use sandboxed execution. Sandboxed execution
      # runs stuff in a container, and since GitLabCI already runs its script
      # in a container this fails to run tests.
      build --spawn_strategy=standalone --genrule_strategy=standalone
      test --test_strategy=standalone --test_output=streamed --nocache_test_results
      EOF
    - rm -rf /builddir
    - cd / && mv $CI_PROJECT_DIR /builddir && mkdir $CI_PROJECT_DIR
    - if [ -d /builddir/bazel-cache ]; then mv /builddir/bazel-cache $CI_PROJECT_DIR/; fi
    - virtualenv -p /usr/bin/python3 /venv
    - source /venv/bin/activate

  variables:
    TEST_TMPDIR: "$CI_PROJECT_DIR/bazel-cache"

  script:
    - cd /builddir && bazel test ...

  cache:
    paths:
      - bazel-cache

pack_ubuntu_14.04:
  image: ubuntu:14.04.4
  stage: pack
  only:
    - tags
  before_script:
    - apt-get update
    - apt-get -y install software-properties-common curl build-essential libssl-dev
    - apt-get -y build-dep python3.4
    - add-apt-repository -y ppa:webupd8team/java
    - apt-get update
    - echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
    - echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
    - apt-get -y install oracle-java8-installer oracle-java8-set-default
    - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" > /etc/apt/sources.list.d/bazel.list
    - curl https://bazel.build/bazel-release.pub.gpg | apt-key add -
    - apt-get update
    - apt-get -y install bazel

  script:
    - ./release.sh

  artifacts:
    paths:
      - /tmp/task_maker

pack_archlinux:
  image: base/archlinux
  stage: pack
  only:
    - tags
  before_script:
    - pacman -Syu --noconfirm jdk8-openjdk bazel gcc make

  script:
    - ./release.sh

  artifacts:
    paths:
      - /tmp/task_maker
