language: cpp
sudo: required
services:
  - docker

matrix:
  include:
    - env:
       - TOOLCHAIN=ubuntu14.04-gcc4.9
    - env:
        - TOOLCHAIN=archlinux

script:
  - docker run --rm
      -e TRAVIS=true
      -e CI=true
      -e TOOLCHAIN=$TOOLCHAIN
      -v $(pwd):/build
      edomora97/task-maker-builder-$TOOLCHAIN:latest
      /build/tools/compile_and_test.sh

after_success:
  - ./build/cpp/task-maker -help