language: cpp
# adds more ram to the build
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:jonathonf/python-3.6"
          packages:
            - g++-4.9
            - git
            - make
            - python3.6
            - python3.6-dev
            - wget
            # only for tests
            - rustc
            # needed for the release
            - zip
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:jonathonf/python-3.6"
          packages:
            - g++-7
            - git
            - make
            - python3.6
            - python3.6-dev
            - wget
            # only for tests
            - rustc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - sourceline: "ppa:jonathonf/python-3.6"
          packages:
            - libstdc++-4.9-dev
            - clang-3.6
            - git
            - make
            - python3.6
            - python3.6-dev
            - wget
            # only for tests
            - rustc
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - sourceline: "ppa:jonathonf/python-3.6"
          packages:
            - libstdc++-4.9-dev
            - clang-5.0
            - git
            - make
            - python3.6
            - python3.6-dev
            - wget
            # only for tests
            - rustc
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

cache:
  directories:
    - hunter-root
    - build


before_install:
  - eval "${MATRIX_EVAL}"

install:
  # install cmake
  - 'wget -O /tmp/cmake.tar.gz "https://cmake.org/files/v3.11/cmake-3.11.1-Linux-x86_64.tar.gz"'
  - '(mkdir /tmp/cmake && tar xf /tmp/cmake.tar.gz -C /tmp/cmake)'
  # install python and pull all the dependencies
  - python3.6 -m venv /tmp/venv --without-pip
  - source /tmp/venv/bin/activate
  - wget https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  # fix missing commands
  - mkdir -p /tmp/bin
  - ln -s $(find /tmp/cmake -name "cmake" -type f -executable) /tmp/bin/cmake
  - ln -sf $(which $CXX) /tmp/bin/c++
  - ln -sf $(which $CC) /tmp/bin/cc
  - 'export PATH=/tmp/bin:$PATH'
  - $CC --version
  - $CXX --version
  - cmake --version

script:
  # invalidate the cache of our build for now
  - rm -rf build
  - cmake -H. -Bbuild -DHUNTER_ROOT=hunter-root
  - cmake --build build
  - python build/python/setup.py install
  # run the tests
  - ( cd build && make test )
  - ./run_tests.sh

after_success:
  - ./build/cpp/manager -help

before_deploy:
  - cmake -H. -Bbuild_rel -DHUNTER_ROOT=hunter-root -DCMAKE_BUILD_TYPE=Release
  - cmake --build build_rel
  - strip -s build_rel/python/task_maker/bin/manager
  - strip -s build_rel/python/task_maker/bin/server
  - strip -s build_rel/python/task_maker/bin/worker
  - chmod +x build_rel/python/setup.py
  - ( cd build_rel/python && zip -r task-maker-$TRAVIS_TAG.zip requirements.txt setup.py task_maker )

deploy:
  provider: releases
  api_key:
    secure: HVF8CkBTelG3qd0R9D8ODEwzYcwU8Sk7wKZ5vDTZajdqSFcHllJfY8UUBJQ2iXH1a2Q9vFqcbd+O44mvKyk/6KGg5xfoxgo4SQvXqvQ/s9AsrMEEOOT/++MMwDEZM6NCSL6CvoH9EOGRw6Dd+XEgS2EiotgvvTi3W9oeq3/qt7UqPqxVgTcqY4ZdIsEHDwPcjcd/B8YZ9G4aq/gRWHoS9OD5exfsMWd+FbN/BD00QJxzVz96IrPXu80d7HpTis34ROO1D+tSBNBqTovfHwTa1A99LLygismY70BofXwrxuanFQH4Jq3kXvMnmZCHFYFqdAw2k5y49yJTwlkf4gmwXQXDfHsos+fSdm5xmuEpUT2asW+riWYcyQ9s0ygZx7FBa3fgamiBSxaP5ogwWX2k41IqV/nPp5S9uATaquyBgSTEQga6xQP68+1igpWi/na77DkH3QS3Fa4UMs6Lef1QTiUkNDSXwdLXV0ljrr3wye6vqz1g6C9/7lPF3Nm5uDy/mYjqZdF/H2mjg+G9smEkSI1/xciDJaTZRxly+SEZRoo1FX7Gk0e58EDgCXHI7Kb8X7ju82hHFpCIgzqDbfxAnmWujBRhy4Qka2wHnezAKOOu7zWqpDUPabcMXg/6eMWtj5h63YAXsalrkYwV4gtyzhOmtICT4MfhzzU0/DmU84U=
  file: build_rel/python/task-maker-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    tags: true
    condition: "$CC = gcc-4.9"
