version: 2

jobs:
  build:
    docker:
      - image: base/archlinux
    steps:
      - run:
          name: Install dependencies
          command: |
            cat > /etc/pacman.d/mirrorlist <<EOF
            Server = http://mirrors.aggregate.org/archlinux/\$repo/os/\$arch
            Server = https://archlinux.surlyjake.com/archlinux/\$repo/os/\$arch
            Server = http://mirrors.evowise.com/archlinux/\$repo/os/\$arch
            Server = http://mirror.rackspace.com/archlinux/\$repo/os/\$arch
            Server = http://mirrors.acm.wpi.edu/archlinux/\$repo/os/\$arch
            Server = http://mirrors.advancedhosters.com/archlinux/\$repo/os/\$arch
            Server = http://ca.us.mirror.archlinux-br.org/\$repo/os/\$arch
            Server = http://il.us.mirror.archlinux-br.org/\$repo/os/\$arch
            Server = http://archlinux.surlyjake.com/archlinux/\$repo/os/\$arch
            Server = https://archlinux.surlyjake.com/archlinux/\$repo/os/\$arch
            EOF
            pacman -Syu --noconfirm --needed base-devel cmake git python go
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: Prepare build
          command: mkdir -p build
      - restore_cache:
          keys:
            - task-maker-v5-{{ arch }}-
      - run:
          name: cmake
          command: cmake .. -DHUNTER_STATUS_DEBUG=ON -DHUNTER_ROOT=hunter-root -DHUNTER_JOBS_NUMBER=4
          working_directory: build
      - run:
          name: make
          command: make -j 4
          working_directory: build
      - store_artifacts:
          path: build
          destination: archlinux-nightly
      - save_cache:
          paths:
            - build
            - hunter-root
          key: task-maker-v5-{{ arch }}-{{ .Revision }}
          when: always

workflows:
  version: 2
  build:
    jobs:
      - build:
          # without this filter the tag builds wont start
          filters:
            tags:
              only: /.*/