version: 2

jobs:
  build:
    docker:
      - image: base/archlinux
    steps:
      - run:
          name: Install dependencies
          command: |
            cat > /etc/pacman.d/mirrorlist <<EOF
            Server = http://mirrors.aggregate.org/archlinux/\$repo/os/\$arch
            Server = https://archlinux.surlyjake.com/archlinux/\$repo/os/\$arch
            Server = http://mirrors.evowise.com/archlinux/\$repo/os/\$arch
            Server = http://mirror.rackspace.com/archlinux/\$repo/os/\$arch
            Server = http://mirrors.acm.wpi.edu/archlinux/\$repo/os/\$arch
            Server = http://mirrors.advancedhosters.com/archlinux/\$repo/os/\$arch
            Server = http://ca.us.mirror.archlinux-br.org/\$repo/os/\$arch
            Server = http://il.us.mirror.archlinux-br.org/\$repo/os/\$arch
            Server = http://archlinux.surlyjake.com/archlinux/\$repo/os/\$arch
            Server = https://archlinux.surlyjake.com/archlinux/\$repo/os/\$arch
            EOF
            cat >> /etc/pacman.conf <<EOF
            [archlinuxfr]
            SigLevel = Never
            Server = http://repo.archlinux.fr/\$arch
            EOF
            useradd builduser
            passwd -d builduser
            pacman -Syu --noconfirm base-devel cmake protobuf yaourt git python
            printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers
            sudo -u builduser bash -c 'yaourt -Sy --noconfirm grpc'
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Prepare build
          command: mkdir -p build
      - restore_cache:
          keys:
            - task-maker-v3-{{ arch }}-
      - run:
          name: cmake
          command: cmake ..
          working_directory: build
      - run:
          name: make
          command: make -j 4
          working_directory: build
      - save_cache:
          paths: build
          key: task-maker-v3-{{ arch }}-{{ .Revision }}
          when: always

# Ubuntu dependencies: g++ make cmake git python3 libprotobuf-dev protobuf-compiler
# https://cmake.org/files/v3.11/cmake-3.11.1-Linux-x86_64.tar.gz
# libgrpc-dev is not enough for Ubuntu 16.04 (it currently does not work with xenial)

workflows:
  version: 2
  build:
    jobs:
      - build:
          # without this filter the tag builds wont start
          filters:
            tags:
              only: /.*/